name: Download and modify file from url

on:
  push:
    branches:
      - main

jobs:
  download_file_and_modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download file from url
      run: curl -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt

    - name: Modify the file using sed command
      run: sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' chnroutes.txt > cnip.list

    - name: Store the modified file
      run: |
        mkdir -p list
        mv -f cnip.list list/
      shell: bash
    - name: Commit the changes
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git add .
        git commit -m "Adding modified chnroutes.txt file"
        git push
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
