name: Download and modify file from url

on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    branches:
      - main

jobs:
  download_file_and_modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download file from url
      run: |
        curl -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt
        curl -o cfip4.txt https://www.cloudflare.com/ips-v4
        curl -o cfip6.txt https://www.cloudflare.com/ips-v6

    - name: Modify the file using sed command
      run: |
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' chnroutes.txt > chinacidr.list
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip4.txt > cloudflare.list
        echo -e '\n' >> cloudflare.list
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip6.txt >> cloudflare.list

    - name: Store the modified file
      run: |
        mkdir -p lists
        mv -f chinacidr.list lists/
        mv -f cloudflare.list lists/
        rm -rf chnroutes.txt cfip4.txt cfip6.txt
      shell: bash

    - name: Check file changes
      id: check_changes
      uses: actions/github-script@v2
      with:
        script: |
          const compareCommits = await github.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: '${{ github.event.before }}',
            head: '${{ github.sha }}'
          });
          const hasChanges = compareCommits.data.files.find(f => f.filename.startsWith('lists/'));
          console.log(hasChanges);
          core.setOutput('hasChanges', hasChanges != null);

    - name: Commit the changes
      if: steps.check_changes.outputs.hasChanges == 'true'
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git add .
        git commit -m "Adding modified chnroutes.txt file"
        git push
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
